2025-03-05 18:14:14,308 INFO    MainThread:25799 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 18:14:14,308 INFO    MainThread:25799 [wandb_setup.py:_flush():67] Configure stats pid to 25799
2025-03-05 18:14:14,308 INFO    MainThread:25799 [wandb_setup.py:_flush():67] Loading settings from /home/pallette/.config/wandb/settings
2025-03-05 18:14:14,308 INFO    MainThread:25799 [wandb_setup.py:_flush():67] Loading settings from /home/pallette/Documents/GitHub/Bachelor/wandb/settings
2025-03-05 18:14:14,308 INFO    MainThread:25799 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 18:14:14,308 INFO    MainThread:25799 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/pallette/Documents/GitHub/Bachelor/wandb/run-20250305_181414-vi3qv9a2/logs/debug.log
2025-03-05 18:14:14,309 INFO    MainThread:25799 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/pallette/Documents/GitHub/Bachelor/wandb/run-20250305_181414-vi3qv9a2/logs/debug-internal.log
2025-03-05 18:14:14,309 INFO    MainThread:25799 [wandb_init.py:init():761] calling init triggers
2025-03-05 18:14:14,309 INFO    MainThread:25799 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'model': 'UNet', 'dataset': 'cropped_objects', 'batch_size': 6, 'val_batch_size': 6, 'learning_rate': 0.0001, 'global_image_size': (650, 650), 'num_epochs': 10, 'gaussian_blur': True, 'post_processing_threshold': 0.5, 'distance_threshold': 10, '_wandb': {}}
2025-03-05 18:14:14,309 INFO    MainThread:25799 [wandb_init.py:init():784] starting backend
2025-03-05 18:14:14,309 INFO    MainThread:25799 [wandb_init.py:init():788] sending inform_init request
2025-03-05 18:14:14,313 INFO    MainThread:25799 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-05 18:14:14,314 INFO    MainThread:25799 [wandb_init.py:init():803] backend started and connected
2025-03-05 18:14:14,315 INFO    MainThread:25799 [wandb_init.py:init():896] updated telemetry
2025-03-05 18:14:14,321 INFO    MainThread:25799 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 18:14:14,824 INFO    MainThread:25799 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 18:14:14,894 INFO    MainThread:25799 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 18:14:14,894 INFO    MainThread:25799 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 18:14:14,894 INFO    MainThread:25799 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 18:14:14,894 INFO    MainThread:25799 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 18:14:14,895 INFO    MainThread:25799 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 18:14:24,332 INFO    Thread-3 (wait_for_termination):25799 [wandb_run.py:_finish():2112] finishing run pallette-personal/lego-keypoint-detection/vi3qv9a2
2025-03-05 18:14:24,333 INFO    Thread-3 (wait_for_termination):25799 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 0
2025-03-05 18:14:24,333 INFO    Thread-3 (wait_for_termination):25799 [wandb_run.py:_restore():2324] restore
2025-03-05 18:14:24,333 INFO    Thread-3 (wait_for_termination):25799 [wandb_run.py:_restore():2330] restore done
2025-03-05 18:14:25,334 INFO    Thread-3 (wait_for_termination):25799 [wandb_run.py:_restore():2324] restore
2025-03-05 18:14:25,334 INFO    Thread-3 (wait_for_termination):25799 [wandb_run.py:_restore():2330] restore done
2025-03-05 18:14:25,334 ERROR   Thread-3 (wait_for_termination):25799 [wandb_run.py:_atexit_cleanup():2363] Problem finishing run
Traceback (most recent call last):
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2354, in _atexit_cleanup
    self._on_finish()
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2611, in _on_finish
    wait_with_progress(
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 23, in wait_with_progress
    return wait_all_with_progress(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 86, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/lib/asyncio_compat.py", line 27, in run
    future = executor.submit(runner.run, fn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 172, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
2025-03-05 18:14:25,346 WARNING MsgRouterThr:25799 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/pallette/Documents/GitHub/Bachelor/.venv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 18:14:25,347 INFO    MsgRouterThr:25799 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
